[package]
name = "fairway_fdb"
version = "0.1.0"
edition = "2021"

[lib]
name = "fairway_fdb"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32"
foundationdb = { version = "0.9", features = ["embedded-fdb-include", "fdb-7_1"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
once_cell = "1"
bytes = "1"

[profile.release]
opt-level = 3
